### ISSUE TITLE
gaierror when using docker-py

### ISSUE THREAD

**Issue by lindycoder** [internap/python-hostsresolver#4]
Hello!

I stumbled on a little problem while using the host resolver and docker-py at the same time:
```
ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
```

Seems like docker-py speaks to the docker engine via unix socket and have a unix socket such as `/var/run/docker.sock` so when this pass into gethostbyname (https://github.com/internap/python-hostsresolver/blob/master/hostsresolver/cache.py#L26) and it's not in the host cache, it invokes socket.gethostbyname which raises a gaierror.... BUT if you pass the socket to socket.connect it will be fine.  

Fix incoming soon :)

**Comment by mat128** [comment]
Good catch :)
